STYLE: Output test data into CMAKE_CURRENT_BINARY_DIR
InsightSoftwareConsortium/ITKIOOMEZarrNGFF pull request #41
Opened 2023-08-04 18:12 UTC by thewtex

This makes the files easier to find. Also, I am wondering if the intermittent failing tests in CI are due to directory existence / permissions.

> terminate called after throwing an instance of 'std::runtime_error'
196
  what():  Could not open /home/runner/work/ITKIOOMEZarrNGFF/build/Testing/Temporary/IOOMEZarrNGFF/cthead1.zarr.zip

2023-08-04 18:28 UTC, tbirdso reviewed
@thewtex Where will test output data be written under the proposed changes? To a `build/test/` directory instead of `build/Testing/Temporary`? This seems like a regression with respect to other modules which use `ITK_TEST_OUTPUT_DIR` by convention.

2023-08-04 20:34 UTC, thewtex commented
> build/test/

Yes.

Other modules should not be outputting to `ITK_TEST_OUTPUT_DIR`. This variable was used pre-ITK-modularization and it is around for backwards compatibility. It will result in all the test files being dumped into the same directory, which makes it hard to distinguish where a file came from and is brittle to clobbering bugs.

2023-08-05 15:02 UTC, tbirdso requested changes
@thewtex 

> Other modules should not be outputting to ITK_TEST_OUTPUT_DIR. This variable was used pre-ITK-modularization and it is around for backwards compatibility. It will result in all the test files being dumped into the same directory, which makes it hard to distinguish where a file came from and is brittle to clobbering bugs.

Thanks for the context. Given that background, I am in favor of standardizing around a test data output directory for ITK modules. I am not sure that `CMAKE_CURRENT_BINARY_DIR` is the right directory to use.

Under the status quo, in my local build we can see that `build/test` aka `CMAKE_CURRENT_BINARY_DIR` already contains an assortment of CMake files to inform the build system:
```sh
path/to/ITKIOOMEZarrNGFF-build/test > $ ls
CMakeFiles/                   IOOMEZarrNGFFTestDriver.vcxproj
CTestTestfile.cmake           IOOMEZarrNGFFTestDriver.vcxproj.filters
INSTALL.dir/                  IOOMEZarrNGFFTestDriver.vcxproj.user
INSTALL.vcxproj               RUN_TESTS.dir/
INSTALL.vcxproj.filters       RUN_TESTS.vcxproj
IOOMEZarrNGFFHeaderTest1.cxx  RUN_TESTS.vcxproj.filters
IOOMEZarrNGFFTestDriver.cxx   cmake_install.cmake
IOOMEZarrNGFFTestDriver.dir/
```

Meanwhile `build/Testing/Temporary` aka `ITK_TEST_OUTPUT_DIR` simply contains test output data along with a few CMake log files:
```sh
path/to/ITKIOOMEZarrNGFF-build/Testing/Temporary > $ ls
652506_Ex_561_Em_593_L3.zarr/  PV6.0_FLASH_FLOAT32.zarr/  cthead1Subregion.mha
CTestCostData.txt              cthead1.mha                cthead1py.zarr/
DzZ_T1seg.zarr/                cthead1.png                memory.zip
LastTest.log                   cthead1.zarr/              tmp.zarr/
LastTestsFailed.log            cthead1.zarr.zip
```

Based on this evidence it's clear that we should not add test output data to `CMAKE_CURRENT_BINARY_DIR`. Moreover, it seems reasonable to keep output data in the `Temporary` folder to indicate that it may be overwritten at any time when tests are run.

If a change to the output directory structure is necessary, I suggest that we revisit and redefine `ITK_TEST_OUTPUT_DIR` in the central ITK repository to point at a new, dedicated test data subfolder at `Testing/Temporary/Output` or similar.

2023-08-07 13:41 UTC, tbirdso commented
> How about using `${ITK_TEST_OUTPUT_DIR}/${itk-module}`, like [InsightSoftwareConsortium/ITK#2241](https://github.com/InsightSoftwareConsortium/ITK/pull/2241) did for ITK proper?

That sounds like a good plan. I am surprised that change is not already available to external modules. Maybe it would be worth digging into the ITK core module to see how that change could be extended.

2023-08-07 13:43 UTC, dzenanz commented
I think that only applies to remotes built during ITK's build.

2023-08-07 17:36 UTC, thewtex commented
> How about using ${ITK_TEST_OUTPUT_DIR}/${itk-module}, like InsightSoftwareConsortium/ITK#2241 did for ITK proper?

This is the case since ITK 5.4rc01.

> terminate called after throwing an instance of 'std::runtime_error'
196
what(): Could not open /home/runner/work/ITKIOOMEZarrNGFF/build/Testing/Temporary/IOOMEZarrNGFF/cthead1.zarr.zip

2023-08-07 17:45 UTC, dzenanz commented
I am also in favor of maintaining the current behavior. The `build/test` directory has some other files, as Tom explained.

2023-08-07 17:46 UTC, thewtex commented
Ok, closing.

Curious that all the tests passed here. We still need to make the CI reliable.

2023-08-07 17:46 UTC, closed without merging