Initial progress
InsightSoftwareConsortium/ITKIOOMEZarrNGFF pull request #6
Opened 2022-08-30 21:22 UTC by dzenanz

2022-08-30 21:23 UTC, dzenanz commented
TODO: try https://github.com/Unidata/netcdf-c/pull/2492/ here.

2022-09-09 16:31 UTC, thewtex requested changes
Please get CI passing

2022-09-09 16:31 UTC, thewtex commented on CMakeLists.txt
> +function(dump_cmake_variables)
remove debug code

2022-09-09 16:31 UTC, thewtex commented on include/itkOMEZarrNGFFImageIO.h
> +  static constexpr unsigned MaximumDimension = 5; // OME-NGFF specifies up to 5D data
5 -> 4 ('c' is the channel / component)

2022-09-09 16:31 UTC, thewtex commented on src/itkOMEZarrNGFFImageIO.cxx
> +  const std::vector<std::string> dimensionNames = { "c", "i", "j", "k", "t" };
i j k to x y z per OME-Zarr

2022-09-20 18:41 UTC, thewtex commented
> -- Building Shared Libraries:     ON

We should turn off shared libraries if possible.

2022-09-20 18:42 UTC, thewtex commented
Linux todo: use ITK's HDF5:

> -- Linking against:      hdf5_cpp-shared;hdf5-shared;/usr/lib/x86_64-linux-gnu/libm.so;itkzlib;/usr/lib/x86_64-linux-gnu/libzip.so;/usr/lib/x86_64-linux-gnu/libbz2.so;libcurl;/usr/lib/x86_64-linux-gnu/libxml2.so

2022-09-20 18:44 UTC, thewtex commented
> ZSTD Support:           no

-> yes

https://open.cdash.org/build/8154414/configure

2022-09-20 18:46 UTC, thewtex commented
> CMake Error at CMakeLists.txt:55 (add_library):
  add_library cannot create ALIAS target "ZLIB::ZLIB" because target
  "itkzlib" is imported but not globally visible.

2022-09-20 18:51 UTC, thewtex commented
For OpenSSL errors, try installing OpenSSL beforehand:

https://github.com/dockcross/dockcross/blob/96d87416f639af0204bdd42553e4b99315ca8476/imagefiles/build-and-install-openssl.sh

Maybe curl on Linux:

https://github.com/dockcross/dockcross/blob/96d87416f639af0204bdd42553e4b99315ca8476/imagefiles/build-and-install-curl.sh

2022-10-04 14:24 UTC, thewtex commented on CMakeLists.txt
> +set(CMAKE_C_FLAGS ${saved_C})
We can add warning exceptions here:

https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/blob/44f22e284f020834ca724c9bea9286530dcff7de/.github/workflows/build-test-package.yml#L98-L102

2022-12-27 22:44 UTC, dzenanz commented
Closing this PR, as I just pushed version ab1a5a47d0ad625232a29943f0861477f7079f42 to master which works fairly well.

2022-12-27 22:44 UTC, closed without merging